name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch: # Allows you to manually click a "Run Workflow" button in GitHub

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Run Test Matrix
        run: npm test

      - name: Build Package
        run: npm run build --if-present

      - name: Publish to NPM (Prerelease)
        run: npm publish --access public --tag alpha --provenance
